### ISSUE TITLE
Add stickers support

### ISSUE THREAD

**Issue by ogarcia** [Aseman-Land/Cutegram#17]
This is for wishlist.

Please add stickers support. At least for incoming messages.

**Comment by realbardia** [comment]
Hi

Stickers, Username and mentions are features that are not supported by libqtelegram currently.
Whenever they add these features to libqtelegram, We'll add this features to cutegram immediately.
So You can request this feature on libqtelegram launchpad page too.

Anyway Thank you for suggestion :)

**Comment by ogarcia** [comment]
I see that in latest version you add Stickers support. I installed it (with latest libqtelegram-aseman-edition) but in Gnome 3.16 cannot see it, only blank spaces :cry:

**Comment by realbardia** [comment]
Hi....
What cutegram package you use? deb, binary installer, PPA or from source?
Also what is your distro?
Cutegram need libqwebp library to show sticker images.
Thank you for reporting.

**Comment by participante0** [comment]
I am using `2.3.0-2aseman-trusty ` from the ppa in Linux Mint 17.1. I can't see the Stickers when I am trying to send or receive it, only blank spaces. I have the package `libwebp5` installed.

Here is an (edited) output:
```
qrc:/qml/Cutegram/AccountMessageMedia.qml:186:21: Unable to assign QSizeF to QSize
qrc:/qml/Cutegram/AccountMessageMedia.qml:176:5: QML Image: Error decoding: file:///home/USER/.config/Cutegram/PHONE_NUMBER/downloads/73330288/1842540969984061.webp.webp: Unsupported image format
```

**Comment by realbardia** [comment]
Please install qt5-image-formats-plugins package on your system. Cutegram needs libqwebp instead of libwebp.
sudo apt-get install qt5-image-formats-plugins

**Comment by ogarcia** [comment]
Sorry for bad info.

I'm using ArchLinux and git source package. But the problem is solved. I don't have installed the extra/qt5-imageformats package. After install it works perfect.

Thanks!

**Comment by farseerfc** [comment]
Hi @ogarcia 
I am maintaining the `cutegram` and `cutegram-git` packages in aur. I added the dependency on `extra/qt5-imageformats` into the `PKGBUILD` of `cutegram-git` 4 days ago, when I found that stickers support is added here in upstream.
The `cutegram` package is more recommended as I will test its dependencies manually whenever I uploaded a new `PKGBUILD`, while the dependencies for `cutegram-git` package may break from time to time. I will try my best to keep up with the changes here, but a delay of 1 or 2 days may be inevitable.
I uploaded cutegram 2.3.0 to aur yesterday, which is only 2 commits behind the git version currently.

**Comment by ogarcia** [comment]
Hi @farseerfc 

I see. Good. Now i'm using you AUR packages. Many thanks for maintain it!

**Comment by realbardia** [comment]
Thank you.
It's fixed on our launchpad PPA too :)

**Comment by participante0** [comment]
Sorry, I still have the same problem after installing `qt5-image-formats-plugins`. I tryed also uninstall it and install it again (`2.3.0-4aseman-trusty`) without success. What could it be?

**Comment by realbardia** [comment]
It's because Qt 5.2. libqwebp isn't exists on Qt 5.2 and trusty repositories.
You can install it manually from source or download Qt 5.3 libqwebp from http://packages.ubuntu.com/utopic/qt5-image-formats-plugins and copy it manually to your system. I hope to work :)

**Comment by participante0** [comment]
Thanks, now it works.

**Comment by realbardia** [comment]
Your Welcome :)

**Comment by adrianiainlam** [comment]
I'm on Ubuntu 14.04.2 but I can't get this to work.
I've tried several things. First I tried to download the package for utopic and install that, but dpkg won't install it because of unsatisfied dependencies.
I then downloaded the Qt 5.3 installer. I don't know where to install them so I didn't change the default location in the installer, which is `/opt/Qt5.3.0/`.
I then copied `/opt/Qt5.3.0/5.3/gcc_64/plugins/imageformats/libqwebp.so` into `/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats` and restarted cutegram, but that didn't work.
I then tried replacing the whole `imageformats` folder with the Qt 5.3 one, and restarted cutegram. That didn't work either, and even the profile pictures of the contacts are not showing.
Please help.

**Comment by realbardia** [comment]
Hi...
Please don't install utopic qt5-image-formats-plugins package. Just extract it, and copy libqwebp.so file to /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/ .
I think you should reinstall trusty qt5-image-formats-plugins package before doing above operation.

**Comment by adrianiainlam** [comment]
That doesn't work either. It gives the same result as taking the libqwebp.so file from the installer. It shows the same debug message in my previous comment (in the edit).

**Comment by realbardia** [comment]
Okkey.
You can download Qt image formats 5.3 source package and build it using Qt 5.2:
http://archive.ubuntu.com/ubuntu/pool/universe/q/qtimageformats-opensource-src/qtimageformats-opensource-src_5.3.0.orig.tar.xz
Also I build it and put it to the site. You can using my build too:
http://aseman.co/downloads/cutegram/extra/libqwebp.so

**Comment by adrianiainlam** [comment]
Great! Your build works like a charm. Thank you :)

**Comment by realbardia** [comment]
Your Welcome :)

**Comment by edoz90** [comment]
Hi! I know that this issue is closed but....I've installed the `cutegram` package of @farseerfc from AUR
and I cannot see my personal stickers:
![stickers](https://cloud.githubusercontent.com/assets/6991986/9154181/0aebe4da-3e84-11e5-9155-629fa04b84db.png)

**Comment by farseerfc** [comment]
@edoz90 hi, from my understanding, cutegram currently support send/receive stickers, but not **sync sticker groups** across devices and clients. You can only right-click stickers and add them to your personal sticker list for now.
I don't know the plans for syncing sticker groups ...

**Comment by realbardia** [comment]
Hi...
We are working to add sticker-set feature for next release. Currently sticker-set feature added to libqtelegram successfully and we are working to add it to the TelegramQML and Cutegram.

**Comment by farseerfc** [comment]
Great to hear that! Thanks for the great app!

**Comment by stormyqq** [comment]
can we add custom stickers to cutegram?
