### ISSUE TITLE
I cannot close secret chat in v2.7

### ISSUE THREAD

**Issue by xavihernandez** [Aseman-Land/Cutegram#175]
Hi, thanks for this unofficial client, especially for secret chats support.
Howerver since v2.7I cannot delete secret chats. When I click on "Delete", a confirmation dialog popups, but even if I click on "Yes" it does nothing.

I have some disconnections too, leading to closing secret chat on the recipient device. And nothing is noticed in my client, then I can talk but I cannot know that my recipient is not receiving my message.

**Comment by xavihernandez** [comment]
Well it seems that since v2.7 there are two ticks, one for sending and he second for reception. Then I think we can know when our recipient is not receiving our messages. But we don't know that secret chat is closed (for exemple in Android client, it is noticed, and you can't send message anymore when secret chat has been closed).

**Comment by xavihernandez** [comment]
This issue is really annoying, because all chats stay opened...
And since I create a new secret chat every day, I have lots of unclosed and useless chats. This was not happening in v2.5

**Comment by xavihernandez** [comment]
No one has this issue ???

**Comment by xavihernandez** [comment]
@Aseman-Land

**Comment by mircsicz** [comment]
I've got the same issue, just installed it because the official client doesnt support secret chats on windows...

But I can't close the damn window of a secret chat, I get the popup but it only delete's the messages in the secret chat!!!

**Comment by Dyras** [comment]
Same issue here

**Comment by realbardia** [comment]
Sorry for this bug. It fixed now and pushed to the both TelegramQml and Cutegram repositories.
It will add to the next minor release.
Thank you for reporting.

**Comment by xavihernandez** [comment]
No new minor release to fix this annoying issue ?

**Comment by xavihernandez** [comment]
Hi @realbardia, do you know when a new release will be out ?
Thanks for the fix tho.

**Comment by selfus** [comment]
Still have this issue, and it happens on normal chats too, without me being able to delete them

**Comment by xavihernandez** [comment]
@selfus I don't know why there is no new release yet. It's been several months now since the fix has been merged.
